#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 28 15:05:12 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
