#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 13 10:25:28 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
